repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: pretty-format-json
        args: [--autofix, --indent, "4"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.15.0
    hooks:
      - id: yamlfmt
        args: [-formatter, scan_folded_as_literal=true]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
